version: '3.1'

services:
  app:
    build: .
    working_dir: /dist
    # environment:
    #   NODE_ENV: production
    ports:
      - '5001:5001'
    volumes:
      - .:/dist/
      - /dist/node_modules